export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const SET_ALL_USER = 'SET_ALL_USER'
export const SET_SEARCH_FILTER = 'SET_SEARCH_FILTER'
export const SET_USER_PREFERENCE_VALUES = 'SET_USER_PREFERENCE_VALUES'
export const SHOW_CHAT_WINDOW = 'SHOW_CHAT_WINDOW'
export const SET_USER_REGISTRATION_STATUS = 'SET_USER_REGISTRATION_STATUS'
export const SHOW_HELP_WINDOW = 'SHOW_HELP_WINDOW'
